name: Android Build

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
              
      - name: Decode app.properties file
        run: |
          echo "${{ secrets.PROPERTIES_FILE }}" > app.properties.asc
          gpg -d --passphrase "${{ secrets.PROPERTIES_PASSWORD }}" --batch app.properties.asc > app.properties

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble
